from .authentication import manager_authenticate, manager_register_user
from .list import manager_list_of_lists,manager_update_list,manager_list_details,manager_create_list,manager_delete_list
from .search import manager_get_history,manager_id_details,manager_all_details,manager_title_details
from .movies import manager_add_movie,manager_movies_in_list,manager_remove_movie